"use strict";
/* ===== «Rincón de lógica» de 2.º ESO: el juego sucio de Schopenhauer (08-10) =====
   Datos de juegosucioview.js (#juegosucio). Quince de las 38 estratagemas de «El arte de tener razón»
   (Schopenhauer, h. 1830), explicadas muy fácil y con su nombre técnico de falacia. Los ejemplos no usan nombres
   de persona inventados (docs/23_nombres_genericos_ipc.md).
   Cada estratagema: n = su número en el libro; dialogo = un ejemplo de instituto en orden (k: "zorro" = quien hace
   trampa, "buho" = la otra persona); img/obra/pie = la ilustración: grabados, litografías y cuadros de dominio público
   (Daumier, Goya, Hogarth, Gillray; Wikimedia Commons), con su pie original traducido. */

const JUEGO_SUCIO = {
  intro: "Arthur Schopenhauer (1788-1860) fue un filósofo alemán con fama de gruñón: mírale el pelo. Hacia 1830 escribió un librito, <em>El arte de tener razón</em>, con 38 «estratagemas»: trucos para ganar una discusión aunque no tengas razón. No lo escribió para que hiciéramos trampas: decía que hay que conocerlas para que no nos las hagan. Aquí tienes 15.",
  pista: "Las ilustraciones son caricaturas y cuadros antiguos de dominio público, sobre todo de Honoré Daumier, que se burló de los abogados de su época: muchos de sus dibujos son, literalmente, estratagemas de Schopenhauer. Fíjate siempre en lo que busca quien hace trampa: no quiere saber quién tiene razón, quiere ganar.",
  retrato: "Arthur Schopenhauer, fotografiado por Johann Schäfer en 1859.",
  estratagemas: [
    { id: "exagerar", n: 1,
      titulo: "Exagera lo que dice el otro",
      tecnico: "Falacia del hombre de paja",
      que: "Cambia lo que ha dicho el otro por una versión exagerada o ridícula, y ataca esa versión, que es facilísima de tumbar. Schopenhauer lo llama «ampliación».",
      dialogo: [{ k: "buho", t: "Podríamos tener menos deberes los viernes." }, { k: "zorro", t: "¡Claro, tú quieres que no estudiemos nunca!" }],
      img: "media/juegosucio/exagerar.jpg", w: 900, h: 1567,
      obra: "Francisco de Goya, <em>El pelele</em> (1791-1792). Museo del Prado.",
      pie: "Cuatro muchachas mantean a un muñeco de paja, un «pelele». Eso hace el hombre de paja: fabrica un muñeco del otro y se divierte zarandeándolo.",
      defensa: "«Yo no he dicho eso.» Repite tu frase exacta, sin aceptar la versión exagerada." },
    { id: "palabras", n: 2,
      titulo: "Juega con las palabras",
      tecnico: "Falacia de equívoco",
      que: "Usa una palabra que tiene dos significados y salta de uno a otro como si fueran lo mismo. Schopenhauer lo llama «homonimia».",
      dialogo: [{ k: "buho", t: "Esa chica es muy lista." }, { k: "zorro", t: "¿Lista? ¡Si todavía se está vistiendo!" }],
      img: "media/juegosucio/palabras.jpg", w: 900, h: 1145,
      obra: "Honoré Daumier, <em>Les Gens de justice</em>, lámina 20 (1845-1848).",
      pie: "«—Querido señor, me es imposible defender su caso… le faltan las piezas más importantes… (aparte) ¡las piezas de cinco francos!» En francés, <em>pièces</em> son a la vez los documentos del juicio y las monedas: el abogado juega con los dos sentidos.",
      defensa: "Pregunta: «¿En qué sentido usas esa palabra?»." },
    { id: "eufemismo", n: 12,
      titulo: "Elige las palabras que te convienen",
      tecnico: "Lenguaje cargado (eufemismo y disfemismo)",
      que: "Para lo tuyo, palabras bonitas; para lo del otro, palabras feas. Así parece que ya tienes razón antes de dar ninguna.",
      dialogo: [{ k: "buho", t: "¡Has copiado mis deberes!" }, { k: "zorro", t: "No he copiado: me he inspirado en tu trabajo." }],
      img: "media/juegosucio/eufemismo.jpg", w: 900, h: 707,
      obra: "Honoré Daumier, <em>Les Gens de justice</em>, lámina 11 (1845-1848).",
      pie: "«—Sí, quieren despojar a este huérfano, al que no llamaré joven, porque tiene cincuenta y siete años; pero no por eso deja de ser huérfano…» Con la palabra «huérfano», el tribunal se imagina a un niño.",
      defensa: "Quita las palabras con disfraz y di lo que pasó con palabras neutras." },
    { id: "dosopciones", n: 13,
      titulo: "Da dos opciones, y que una sea horrible",
      tecnico: "Falso dilema",
      que: "Presenta solo dos caminos, uno de ellos espantoso, para que el otro parezca la única salida. Como si no hubiera más.",
      dialogo: [{ k: "zorro", t: "O me dejas tus apuntes, o es que no eres mi amigo." }, { k: "buho", t: "¿Y no hay una tercera puerta?" }],
      img: "media/juegosucio/dosopciones.jpg", w: 900, h: 762,
      obra: "James Gillray, <em>Britannia entre Escila y Caribdis</em> (1793). Biblioteca del Congreso, Washington.",
      pie: "La barca de la Constitución solo puede estrellarse contra la roca de la «Democracia» o hundirse en el remolino del «Poder arbitrario»… salvo que siga el rumbo de su piloto, el primer ministro. Si solo enseñas dos peligros, tu camino parece el único.",
      defensa: "Busca la tercera opción: casi siempre hay más de dos." },
    { id: "victoria", n: 14,
      titulo: "Canta victoria aunque no hayas ganado",
      tecnico: "Proclamar el triunfo (no es una falacia: es un farol)",
      que: "Al final de la discusión, anuncia muy seguro que has ganado. Si lo dices con aplomo, mucha gente se lo cree.",
      dialogo: [{ k: "zorro", t: "Así que gano yo, como queríamos demostrar." }, { k: "buho", t: "Pero si no has demostrado nada…" }],
      img: "media/juegosucio/victoria.jpg", w: 900, h: 1209,
      obra: "Honoré Daumier, <em>Les Gens de justice</em>, lámina 35 (1845-1848).",
      pie: "«—Ha perdido usted el pleito, es verdad… pero habrá disfrutado mucho oyéndome defenderlo.»",
      defensa: "Pide que resuma qué ha demostrado y con qué razones." },
    { id: "tutambien", n: 16,
      titulo: "«¡Pues tú también!»",
      tecnico: "Falacia tu quoque (ad hominem)",
      que: "En vez de responder a la crítica, recuerda que el otro hizo lo mismo. Como si eso cambiara si está bien o mal.",
      dialogo: [{ k: "buho", t: "No deberías tirar papeles al suelo." }, { k: "zorro", t: "¡Pues el otro día tú también tiraste uno!" }],
      img: "media/juegosucio/tutambien.jpg", w: 900, h: 727,
      obra: "Honoré Daumier, <em>Les Gens de justice</em>, lámina 14 (1845-1848).",
      pie: "«—Oiga, colega: hoy va a defender contra mí exactamente lo que yo defendía hace tres semanas en un caso idéntico… ¡Y yo le repetiré lo que usted me contestaba entonces!» Echarle en cara a alguien lo que dijo o hizo antes es el corazón del «¡pues tú también!».",
      defensa: "«Puede que yo también lo hiciera. ¿Está bien tirarlos o no?»" },
    { id: "pendiente", n: 24,
      titulo: "Saca consecuencias exageradas",
      tecnico: "Pendiente resbaladiza",
      que: "Encadena consecuencias cada vez peores hasta llegar a un desastre, como si cada paso llevara al siguiente sin remedio. Schopenhauer lo llama «consecuencias forzadas».",
      dialogo: [{ k: "buho", t: "Me gustaría volver a casa a las diez." }, { k: "zorro", t: "Hoy a las diez, mañana a las doce… ¡y en un mes vivirás en la calle!" }],
      img: "media/juegosucio/pendiente.jpg", w: 900, h: 796,
      obra: "William Hogarth, <em>La carrera del libertino</em>, lámina 4 (1735).",
      pie: "Hogarth contó en ocho grabados la caída de un joven que hereda una fortuna: fiestas, deudas, cárcel y manicomio. En esta lámina lo detienen por deudas. La pendiente resbaladiza cuenta así cualquier primer paso: como si llevara sin remedio al último.",
      defensa: "Pregunta por cada paso: «¿Por qué tendría que pasar eso?»." },
    { id: "publico", n: 28,
      titulo: "Haz reír al público",
      tecnico: "Apelar al ridículo (argumentum ad auditores)",
      que: "Suelta una broma sobre lo que ha dicho el otro. Si el público se ríe, parece que has ganado, aunque no hayas dado ninguna razón.",
      dialogo: [{ k: "buho", t: "Las abejas son importantísimas para nuestra comida." }, { k: "zorro", t: "¡Ja! ¿Y ahora te vas a casar con una abeja?" }],
      img: "media/juegosucio/publico.jpg", w: 900, h: 1006,
      obra: "William Hogarth, <em>El público que ríe</em> (1733). National Gallery of Art, Washington.",
      pie: "El público de un teatro se desternilla de risa; solo los músicos de la orquesta, delante, siguen serios. Cuando la gente se ríe, parece que el chiste ha ganado la discusión.",
      defensa: "Espera a que pasen las risas y vuelve a tu argumento: una broma no es una razón." },
    { id: "cambiartema", n: 29,
      titulo: "Cambia de tema cuando vas perdiendo",
      tecnico: "Pista falsa (en inglés, «red herring»)",
      que: "Saca otro asunto que llame la atención para que todo el mundo se olvide de lo que se discutía.",
      dialogo: [{ k: "buho", t: "Has llegado tarde tres veces esta semana." }, { k: "zorro", t: "¿Y habéis visto qué zapatillas lleva hoy el profe?" }],
      img: "media/juegosucio/cambiartema.jpg", w: 900, h: 683,
      obra: "Honoré Daumier, <em>Les Gens de justice</em>, lámina 30 (1845-1848).",
      pie: "«El abogado que se desmaya: último recurso cuando la causa está muy enferma.» Si todo el mundo mira al desmayado, nadie mira las pruebas.",
      defensa: "«Luego hablamos de eso. Ahora estábamos hablando de…»" },
    { id: "autoridad", n: 30,
      titulo: "Tira de autoridad",
      tecnico: "Falacia de autoridad (ad verecundiam)",
      que: "En vez de razones, cita a alguien famoso o importante, aunque no sepa nada del tema.",
      dialogo: [{ k: "buho", t: "¿Por qué crees que ese champú cura la caspa?" }, { k: "zorro", t: "¡Lo dice un futbolista con tres millones de seguidores!" }],
      img: "media/juegosucio/autoridad.jpg", w: 900, h: 1258,
      obra: "Francisco de Goya, <em>Capricho 37: ¿Si sabrá más el discípulo?</em> (1799). Museo del Prado.",
      pie: "Un asno hace de maestro y le enseña el abecedario a un burrito. Que alguien ocupe el sitio del maestro no quiere decir que sepa de lo que habla.",
      defensa: "Pregunta: «¿Sabe de eso? ¿Qué gana diciéndolo?»." },
    { id: "etiqueta", n: 32,
      titulo: "Ponle una etiqueta fea",
      tecnico: "Culpa por asociación",
      que: "Mete lo que dice el otro en una categoría que suena mal, y ya no hace falta discutirlo.",
      dialogo: [{ k: "buho", t: "A mí me gusta escuchar la radio." }, { k: "zorro", t: "¡Eso es de abuelos!" }],
      img: "media/juegosucio/etiqueta.jpg", w: 900, h: 1100,
      obra: "Honoré Daumier, <em>Les Bas-bleus</em> (1844).",
      pie: "«<em>Bas-bleu</em>» («marisabidilla») era la etiqueta con la que se ridiculizaba a las mujeres que escribían, y Daumier le dedicó una serie entera. Con una etiqueta así ya no hace falta escuchar lo que alguien dice.",
      defensa: "La etiqueta no es una razón: «¿Y qué tiene de malo?»." },
    { id: "interes", n: 35,
      titulo: "Toca el bolsillo, no la cabeza",
      tecnico: "Apelar a las consecuencias (ad consequentiam)",
      que: "No intentes convencer con razones: haz ver al otro, o al público, que su idea le perjudica. Schopenhauer decía que, si se puede usar, hace innecesarias todas las demás.",
      dialogo: [{ k: "buho", t: "Propongo dejar los móviles en casa en la excursión." }, { k: "zorro", t: "Ya, ¿y quién hará las fotos para vuestras redes?" }],
      img: "media/juegosucio/interes.jpg", w: 900, h: 731,
      obra: "Honoré Daumier, <em>Les Gens de justice</em>, lámina 6 (1845-1848).",
      pie: "«Un abogado que, evidentemente, está lleno de la convicción más íntima… de que su cliente le pagará bien.» A veces la razón más fuerte de alguien no es la que dice, sino lo que gana.",
      defensa: "Que algo no te convenga no lo hace falso. Separa «¿es verdad?» de «¿me interesa?»." },
    { id: "palabreria", n: 36,
      titulo: "Lía al otro con palabrería",
      tecnico: "Jerga vacía (ofuscación)",
      que: "Suelta frases largas y difíciles que suenan a muy sabias. El otro, por no parecer tonto, no se atreve a preguntar.",
      dialogo: [{ k: "zorro", t: "Desde una perspectiva holística, tu propuesta carece de sinergias." }, { k: "buho", t: "¿Y eso qué significa?" }],
      img: "media/juegosucio/palabreria.jpg", w: 900, h: 1276,
      obra: "Francisco de Goya, <em>Capricho 53: ¡Qué pico de oro!</em> (1799). Museo del Prado.",
      pie: "Un loro predica desde lo alto y un público de señores serios lo escucha embobado. Hablar bonito y difícil no es lo mismo que decir algo.",
      defensa: "Pregunta sin miedo: «¿Me lo explicas con palabras sencillas?»." },
    { id: "pruebamala", n: 37,
      titulo: "Tumba la prueba mala y da la idea por tumbada",
      tecnico: "Falacia de la falacia (ad logicam)",
      que: "Si el otro defiende una idea verdadera con una mala razón, ataca la razón y haz como si la idea fuera falsa.",
      dialogo: [{ k: "buho", t: "Fumar es malo porque lo dice mi abuela." }, { k: "zorro", t: "¡Tu abuela no es médica! O sea, que fumar no es malo." }],
      img: "media/juegosucio/pruebamala.jpg", w: 900, h: 750,
      obra: "Honoré Daumier, <em>Les Gens de justice</em>, lámina 17 (1845-1848).",
      pie: "«—Testigo, sería importante que nos contara con todo detalle qué hizo el pasado 12 de abril. —Pero, señor presidente, si hace nueve meses… —¡No importa, cuente!» Si el testigo no recuerda los detalles, parece que todo lo que dice es falso, aunque no lo sea.",
      defensa: "Una mala razón no hace falsa una idea: busca una razón mejor." },
    { id: "insultar", n: 38,
      titulo: "Si pierdes, insulta",
      tecnico: "Ataque a la persona (ad hominem)",
      que: "Es la última estratagema: cuando ya no tienes nada que decir, ataca a la persona en vez de a lo que dice. Schopenhauer aconseja no discutir con quien juega así.",
      dialogo: [{ k: "buho", t: "Tus datos están mal: aquí no viven cien millones de personas." }, { k: "zorro", t: "¡Y tú qué sabrás, si suspendiste mates!" }],
      img: "media/juegosucio/insultar.jpg", w: 900, h: 1196,
      obra: "Honoré Daumier, <em>Les Gens de justice</em>, lámina 32 (1845-1848).",
      pie: "«—Deje que hablen un poco mal de usted… deje… Dentro de un momento insultaré yo a toda la familia de su adversario.»",
      defensa: "«Puede ser, pero ¿mis datos están bien o mal?» Y si sigue insultando, deja la discusión." }
  ]
};
