"use strict";
/* ===== «Rincón de lógica» de 2.º ESO: el juego sucio de Schopenhauer (08-10) =====
   Datos de juegosucioview.js (#juegosucio). Veinticinco de las 38 estratagemas de «El arte de tener razón»
   (Schopenhauer, h. 1830), explicadas muy fácil y con su nombre técnico de falacia. Los ejemplos no usan nombres
   de persona inventados (docs/23_nombres_genericos_ipc.md).
   Cada estratagema: n = su número en el libro; dialogo = un ejemplo de instituto en orden (k: "zorro" = quien hace
   trampa, "buho" = la otra persona); img/obra/pie = la ilustración: grabados, litografías y cuadros de dominio público
   (Daumier, Goya, Hogarth, Gillray; Wikimedia Commons), con su pie original traducido. */

const JUEGO_SUCIO = {
  intro: "Arthur Schopenhauer (1788-1860) fue un filósofo alemán con fama de gruñón: mírale el pelo. Hacia 1830 escribió un librito, <em>El arte de tener razón</em>, con 38 «estratagemas»: trucos para ganar una discusión aunque no tengas razón. No lo escribió para que hiciéramos trampas: decía que hay que conocerlas para que no nos las hagan. Aquí tienes 25.",
  pista: "Las ilustraciones son caricaturas y cuadros antiguos de dominio público, sobre todo de Honoré Daumier, que se burló de los abogados de su época: muchos de sus dibujos son, literalmente, estratagemas de Schopenhauer. Fíjate siempre en lo que busca quien hace trampa: no quiere saber quién tiene razón, quiere ganar.",
  retrato: "Arthur Schopenhauer, fotografiado por Johann Schäfer en 1859.",
  estratagemas: [
    { id: "exagerar", n: 1,
      titulo: "Exagera lo que dice el otro",
      tecnico: "Falacia del hombre de paja",
      que: "Cambia lo que ha dicho el otro por una versión exagerada o ridícula, y ataca esa versión, que es facilísima de tumbar. Schopenhauer lo llama «ampliación».",
      dialogo: [{ k: "buho", t: "Podríamos tener menos deberes los viernes." }, { k: "zorro", t: "¡Claro, tú quieres que no estudiemos nunca!" }],
      img: "media/juegosucio/exagerar.jpg", w: 900, h: 1567,
      obra: "Francisco de Goya, <em>El pelele</em> (1791-1792). Museo del Prado.",
      pie: "Cuatro muchachas mantean a un muñeco de paja, un «pelele». Eso hace el hombre de paja: fabrica un muñeco del otro y se divierte zarandeándolo.",
      defensa: "«Yo no he dicho eso.» Repite tu frase exacta, sin aceptar la versión exagerada." },
    { id: "palabras", n: 2,
      titulo: "Juega con las palabras",
      tecnico: "Falacia de equívoco",
      que: "Usa una palabra que tiene dos significados y salta de uno a otro como si fueran lo mismo. Schopenhauer lo llama «homonimia».",
      dialogo: [{ k: "buho", t: "Esa chica es muy lista." }, { k: "zorro", t: "¿Lista? ¡Si todavía se está vistiendo!" }],
      img: "media/juegosucio/palabras.jpg", w: 900, h: 1145,
      obra: "Honoré Daumier, <em>Les Gens de justice</em>, lámina 20 (1845-1848).",
      pie: "«—Querido señor, me es imposible defender su caso… le faltan las piezas más importantes… (aparte) ¡las piezas de cinco francos!» En francés, <em>pièces</em> son a la vez los documentos del juicio y las monedas: el abogado juega con los dos sentidos.",
      defensa: "Pregunta: «¿En qué sentido usas esa palabra?»." },
    { id: "relativo", n: 3,
      titulo: "Quita el «en algunos casos»",
      tecnico: "Falacia secundum quid (de lo relativo a lo absoluto)",
      que: "Si el otro dice algo que vale en un caso o en un sentido, haz como si lo dijera de todos los casos, y tumba esa versión.",
      dialogo: [{ k: "buho", t: "Para mí, el móvil puede ser útil para estudiar." }, { k: "zorro", t: "¿Ah, sí? ¿Entonces hay que dejar el móvil en los exámenes?" }],
      img: "media/juegosucio/relativo.jpg", w: 900, h: 721,
      obra: "Honoré Daumier, <em>Les Gens de justice</em>, lámina 15 (1845-1848).",
      pie: "«—Tenía usted hambre… tenía hambre… eso no es una razón… ¡Yo también tengo hambre casi todos los días y no robo por eso!» El juez, bien comido, iguala su apetito con el hambre de un pobre: se salta el «en qué circunstancias».",
      defensa: "«He dicho para estudiar, no en el examen.» Recupera el «en qué caso» de tu frase." },
    { id: "circulo", n: 6,
      titulo: "Da por hecho lo que hay que demostrar",
      tecnico: "Petición de principio (razonamiento circular)",
      que: "Mete en tus razones, disimulado con otras palabras, justo aquello que se está discutiendo. Parece que lo has demostrado, pero solo lo has repetido.",
      dialogo: [{ k: "buho", t: "¿Por qué dices que esa web es fiable?" }, { k: "zorro", t: "Porque todo lo que publica es verdad." }],
      img: "media/juegosucio/circulo.jpg", w: 900, h: 1185,
      obra: "Honoré Daumier, <em>Les Gens de justice</em>, lámina 12 (1845-1848).",
      pie: "«—¡Y pensar que hay tres de mis acusados a los que no he podido hacer condenar!… ¡Voy a perder mi reputación!» El fiscal da por hecho que eran culpables, y eso era justo lo que había que demostrar en el juicio.",
      defensa: "«Eso es lo que tienes que demostrar.» Pide una razón que no sea la misma idea con otras palabras." },
    { id: "enfadar", n: 8,
      titulo: "Haz que el otro se enfade",
      tecnico: "Provocación (no es una falacia: es una táctica)",
      que: "Pincha al otro hasta que se enfade. Enfadado razona peor, dice cosas que no piensa y parece que pierde.",
      dialogo: [{ k: "zorro", t: "Uy, qué rojo te pones. ¿Te molesta que te lleven la contraria?" }, { k: "buho", t: "¡Que no me molesta, que…!" }],
      img: "media/juegosucio/enfadar.jpg", w: 900, h: 1200,
      obra: "Honoré Daumier, <em>Les Gens de justice</em>, lámina 9 (1845-1848).",
      pie: "«—¡Me ha injuriado usted en su alegato, pero sabré obligarle a darme explicaciones!… —Sepa, caballero, que no le temo…» Dos abogados se han picado: ya no discuten el caso, discuten entre ellos.",
      defensa: "Respira y vuelve al tema: que te enfades no hace verdad lo que dice el otro." },
    { id: "generalizar", n: 11,
      titulo: "Saca la regla de unos pocos casos",
      tecnico: "Generalización apresurada",
      que: "Consigue que el otro admita unos cuantos casos y luego da por admitida la regla general, aunque nadie la haya aceptado. Schopenhauer lo llama «inducción».",
      dialogo: [{ k: "zorro", t: "Tu primo suspendió y tu vecina también: los de ese instituto son todos unos vagos." }, { k: "buho", t: "¿Por dos personas?" }],
      img: "media/juegosucio/generalizar.jpg", w: 900, h: 626,
      obra: "John James Audubon, <em>Cisne trompetero</em>, lámina 406 de <em>Las aves de América</em> (1838).",
      pie: "Durante siglos, todos los cisnes que se veían en Europa eran blancos, y se daba por hecho que todos los cisnes lo eran. Era una generalización: muchísimos casos, pero no todos.",
      defensa: "«¿Cuántos casos has mirado?» Unos pocos casos no hacen una regla." },
    { id: "eufemismo", n: 12,
      titulo: "Elige las palabras que te convienen",
      tecnico: "Lenguaje cargado (eufemismo y disfemismo)",
      que: "Para lo tuyo, palabras bonitas; para lo del otro, palabras feas. Así parece que ya tienes razón antes de dar ninguna.",
      dialogo: [{ k: "buho", t: "¡Has copiado mis deberes!" }, { k: "zorro", t: "No he copiado: me he inspirado en tu trabajo." }],
      img: "media/juegosucio/eufemismo.jpg", w: 900, h: 707,
      obra: "Honoré Daumier, <em>Les Gens de justice</em>, lámina 11 (1845-1848).",
      pie: "«—Sí, quieren despojar a este huérfano, al que no llamaré joven, porque tiene cincuenta y siete años; pero no por eso deja de ser huérfano…» Con la palabra «huérfano», el tribunal se imagina a un niño.",
      defensa: "Quita las palabras con disfraz y di lo que pasó con palabras neutras." },
    { id: "dosopciones", n: 13,
      titulo: "Da dos opciones, y que una sea horrible",
      tecnico: "Falso dilema",
      que: "Presenta solo dos caminos, uno de ellos espantoso, para que el otro parezca la única salida. Como si no hubiera más.",
      dialogo: [{ k: "zorro", t: "O me dejas tus apuntes, o es que no eres mi amigo." }, { k: "buho", t: "¿Y no hay una tercera puerta?" }],
      img: "media/juegosucio/dosopciones.jpg", w: 900, h: 762,
      obra: "James Gillray, <em>Britannia entre Escila y Caribdis</em> (1793). Biblioteca del Congreso, Washington.",
      pie: "La barca de la Constitución solo puede estrellarse contra la roca de la «Democracia» o hundirse en el remolino del «Poder arbitrario»… salvo que siga el rumbo de su piloto, el primer ministro. Si solo enseñas dos peligros, tu camino parece el único.",
      defensa: "Busca la tercera opción: casi siempre hay más de dos." },
    { id: "victoria", n: 14,
      titulo: "Canta victoria aunque no hayas ganado",
      tecnico: "Proclamar el triunfo (no es una falacia: es un farol)",
      que: "Al final de la discusión, anuncia muy seguro que has ganado. Si lo dices con aplomo, mucha gente se lo cree.",
      dialogo: [{ k: "zorro", t: "Así que gano yo, como queríamos demostrar." }, { k: "buho", t: "Pero si no has demostrado nada…" }],
      img: "media/juegosucio/victoria.jpg", w: 900, h: 1209,
      obra: "Honoré Daumier, <em>Les Gens de justice</em>, lámina 35 (1845-1848).",
      pie: "«—Ha perdido usted el pleito, es verdad… pero habrá disfrutado mucho oyéndome defenderlo.»",
      defensa: "Pide que resuma qué ha demostrado y con qué razones." },
    { id: "tutambien", n: 16,
      titulo: "«¡Pues tú también!»",
      tecnico: "Falacia tu quoque (ad hominem)",
      que: "En vez de responder a la crítica, recuerda que el otro hizo lo mismo. Como si eso cambiara si está bien o mal.",
      dialogo: [{ k: "buho", t: "No deberías tirar papeles al suelo." }, { k: "zorro", t: "¡Pues el otro día tú también tiraste uno!" }],
      img: "media/juegosucio/tutambien.jpg", w: 900, h: 727,
      obra: "Honoré Daumier, <em>Les Gens de justice</em>, lámina 14 (1845-1848).",
      pie: "«—Oiga, colega: hoy va a defender contra mí exactamente lo que yo defendía hace tres semanas en un caso idéntico… ¡Y yo le repetiré lo que usted me contestaba entonces!» Echarle en cara a alguien lo que dijo o hizo antes es el corazón del «¡pues tú también!».",
      defensa: "«Puede que yo también lo hiciera. ¿Está bien tirarlos o no?»" },
    { id: "distincion", n: 17,
      titulo: "Sácate una distinción de la manga",
      tecnico: "Alegato especial (excepción hecha a medida)",
      que: "Cuando te pillan, inventa una diferencia que nadie había mencionado para escaparte: «esto es distinto porque…».",
      dialogo: [{ k: "buho", t: "Dijiste que nunca copias, y te he visto copiando." }, { k: "zorro", t: "Eso no era copiar: era comparar respuestas." }],
      img: "media/juegosucio/distincion.jpg", w: 900, h: 1213,
      obra: "Honoré Daumier, <em>Les Gens de justice</em>, lámina 19 (1845-1848).",
      pie: "«—Lo que me fastidia es que me acusan de doce robos. —¿Doce?… ¡Mejor!… Alegaré monomanía.» Con una distinción nueva, doce robos dejan de ser robos y pasan a ser una manía.",
      defensa: "Pregunta: «¿Esa diferencia la habías dicho antes, o te la acabas de inventar?»." },
    { id: "general", n: 19,
      titulo: "Si te piden algo concreto, vete a lo general",
      tecnico: "Respuesta vaga (evasiva)",
      que: "Cuando el otro pide una prueba concreta, contesta con grandes frases generales, en las que nadie puede llevarte la contraria.",
      dialogo: [{ k: "buho", t: "¿En qué datos te basas para decir que ha bajado el paro?" }, { k: "zorro", t: "Mira, la economía es un sistema complejo en el que todo influye en todo." }],
      img: "media/juegosucio/general.jpg", w: 900, h: 712,
      obra: "Honoré Daumier, <em>Les Gens de justice</em>, lámina 33 (1845-1848).",
      pie: "«Una peroración a lo Demóstenes.» El abogado alza los brazos y remata su alegato con un gran discurso. Cuanto más general y grandioso, menos se puede comprobar.",
      defensa: "«Vale, pero ¿qué dato concreto tienes?» Vuelve a pedir lo concreto." },
    { id: "pendiente", n: 24,
      titulo: "Saca consecuencias exageradas",
      tecnico: "Pendiente resbaladiza",
      que: "Encadena consecuencias cada vez peores hasta llegar a un desastre, como si cada paso llevara al siguiente sin remedio. Schopenhauer lo llama «consecuencias forzadas».",
      dialogo: [{ k: "buho", t: "Me gustaría volver a casa a las diez." }, { k: "zorro", t: "Hoy a las diez, mañana a las doce… ¡y en un mes vivirás en la calle!" }],
      img: "media/juegosucio/pendiente.jpg", w: 900, h: 796,
      obra: "William Hogarth, <em>La carrera del libertino</em>, lámina 4 (1735).",
      pie: "Hogarth contó en ocho grabados la caída de un joven que hereda una fortuna: fiestas, deudas, cárcel y manicomio. En esta lámina lo detienen por deudas. La pendiente resbaladiza cuenta así cualquier primer paso: como si llevara sin remedio al último.",
      defensa: "Pregunta por cada paso: «¿Por qué tendría que pasar eso?»." },
    { id: "contraejemplo", n: 25,
      titulo: "Busca un solo caso en contra",
      tecnico: "Contraejemplo (instantia)",
      que: "Si el otro dice que algo pasa siempre, basta un caso en contra para tumbarlo. Esta vez no es trampa: es la jugada limpia que Schopenhauer recomienda contra las afirmaciones generales.",
      dialogo: [{ k: "zorro", t: "Todos los cisnes son blancos: lo sabe todo el mundo." }, { k: "buho", t: "Pues en Australia los hay negros." }],
      img: "media/juegosucio/contraejemplo.jpg", w: 900, h: 1204,
      obra: "John Gerrard Keulemans, <em>Cisne negro</em> (1869).",
      pie: "En 1697, unos navegantes europeos vieron cisnes negros en Australia. Un solo caso bastó para tumbar la regla «todos los cisnes son blancos». Por eso el «cisne negro» es el ejemplo clásico de contraejemplo.",
      defensa: "Si el contraejemplo es de verdad, no se puede parar: hay que corregir la regla («casi todos…»). Eso sí, comprueba que el caso sea real." },
    { id: "vuelta", n: 26,
      titulo: "Dale la vuelta a su argumento",
      tecnico: "Retorsión del argumento (retorsio argumenti)",
      que: "Usa el mismo argumento del otro para sacar la conclusión contraria. El ejemplo es del propio Schopenhauer.",
      dialogo: [{ k: "buho", t: "Es pequeño: no le castigues." }, { k: "zorro", t: "Precisamente porque es pequeño hay que corregirle, para que no coja malas costumbres." }],
      img: "media/juegosucio/vuelta.jpg", w: 900, h: 1143,
      obra: "Honoré Daumier, <em>Les Gens de justice</em>, lámina 22 (1845-1848).",
      pie: "«Defiende al huérfano y a la viuda… salvo cuando ataca a la viuda y al huérfano.» El mismo argumento sirve para un lado y para el otro, según quién pague.",
      defensa: "Mira si de verdad se sigue lo contrario, o si solo suena ingenioso." },
    { id: "publico", n: 28,
      titulo: "Haz reír al público",
      tecnico: "Apelar al ridículo (argumentum ad auditores)",
      que: "Suelta una broma sobre lo que ha dicho el otro. Si el público se ríe, parece que has ganado, aunque no hayas dado ninguna razón.",
      dialogo: [{ k: "buho", t: "Las abejas son importantísimas para nuestra comida." }, { k: "zorro", t: "¡Ja! ¿Y ahora te vas a casar con una abeja?" }],
      img: "media/juegosucio/publico.jpg", w: 900, h: 1006,
      obra: "William Hogarth, <em>El público que ríe</em> (1733). National Gallery of Art, Washington.",
      pie: "El público de un teatro se desternilla de risa; solo los músicos de la orquesta, delante, siguen serios. Cuando la gente se ríe, parece que el chiste ha ganado la discusión.",
      defensa: "Espera a que pasen las risas y vuelve a tu argumento: una broma no es una razón." },
    { id: "cambiartema", n: 29,
      titulo: "Cambia de tema cuando vas perdiendo",
      tecnico: "Pista falsa (en inglés, «red herring»)",
      que: "Saca otro asunto que llame la atención para que todo el mundo se olvide de lo que se discutía.",
      dialogo: [{ k: "buho", t: "Has llegado tarde tres veces esta semana." }, { k: "zorro", t: "¿Y habéis visto qué zapatillas lleva hoy el profe?" }],
      img: "media/juegosucio/cambiartema.jpg", w: 900, h: 683,
      obra: "Honoré Daumier, <em>Les Gens de justice</em>, lámina 30 (1845-1848).",
      pie: "«El abogado que se desmaya: último recurso cuando la causa está muy enferma.» Si todo el mundo mira al desmayado, nadie mira las pruebas.",
      defensa: "«Luego hablamos de eso. Ahora estábamos hablando de…»" },
    { id: "autoridad", n: 30,
      titulo: "Tira de autoridad",
      tecnico: "Falacia de autoridad (ad verecundiam)",
      que: "En vez de razones, cita a alguien famoso o importante, aunque no sepa nada del tema.",
      dialogo: [{ k: "buho", t: "¿Por qué crees que ese champú cura la caspa?" }, { k: "zorro", t: "¡Lo dice un futbolista con tres millones de seguidores!" }],
      img: "media/juegosucio/autoridad.jpg", w: 900, h: 1258,
      obra: "Francisco de Goya, <em>Capricho 37: ¿Si sabrá más el discípulo?</em> (1799). Museo del Prado.",
      pie: "Un asno hace de maestro y le enseña el abecedario a un burrito. Que alguien ocupe el sitio del maestro no quiere decir que sepa de lo que habla.",
      defensa: "Pregunta: «¿Sabe de eso? ¿Qué gana diciéndolo?»." },
    { id: "ironia", n: 31,
      titulo: "Hazte el tonto con ironía",
      tecnico: "Falsa incompetencia irónica",
      que: "Cuando no tienes respuesta, di con falsa modestia que «eso es demasiado profundo para ti». Así parece que lo que dice el otro es un galimatías.",
      dialogo: [{ k: "buho", t: "Si todos copiamos, la nota ya no mide lo que sabemos." }, { k: "zorro", t: "Ay, eso es demasiado profundo para mí: no lo entiendo." }],
      img: "media/juegosucio/ironia.jpg", w: 900, h: 1233,
      obra: "Francisco de Goya, <em>Capricho 50: Los Chinchillas</em> (1799). Museo del Prado.",
      pie: "Dos hombres con las orejas cerradas con candado y los ojos cerrados se dejan dar de comer a cucharadas. Quien no quiere entender, no entiende.",
      defensa: "«Te lo explico más despacio.» Y si de verdad no lo entiende, que diga qué parte." },
    { id: "etiqueta", n: 32,
      titulo: "Ponle una etiqueta fea",
      tecnico: "Culpa por asociación",
      que: "Mete lo que dice el otro en una categoría que suena mal, y ya no hace falta discutirlo.",
      dialogo: [{ k: "buho", t: "A mí me gusta escuchar la radio." }, { k: "zorro", t: "¡Eso es de abuelos!" }],
      img: "media/juegosucio/etiqueta.jpg", w: 900, h: 1100,
      obra: "Honoré Daumier, <em>Les Bas-bleus</em> (1844).",
      pie: "«<em>Bas-bleu</em>» («marisabidilla») era la etiqueta con la que se ridiculizaba a las mujeres que escribían, y Daumier le dedicó una serie entera. Con una etiqueta así ya no hace falta escuchar lo que alguien dice.",
      defensa: "La etiqueta no es una razón: «¿Y qué tiene de malo?»." },
    { id: "teoria", n: 33,
      titulo: "«En teoría sí, en la práctica no»",
      tecnico: "Falso contraste entre teoría y práctica",
      que: "Admite las razones del otro, pero di que «en la práctica» no funcionan. Schopenhauer responde que, si algo es correcto en teoría, tiene que serlo en la práctica: si falla, hay un error en la teoría.",
      dialogo: [{ k: "buho", t: "Si estudias un poco cada día, el examen te sale mejor." }, { k: "zorro", t: "Eso en teoría está muy bien, pero en la práctica no funciona." }],
      img: "media/juegosucio/teoria.jpg", w: 900, h: 1114,
      obra: "Honoré Daumier, <em>Búsqueda infructuosa del planeta Leverrier</em> (1846). National Gallery of Art, Washington.",
      pie: "En 1846, el astrónomo Le Verrier calculó sobre el papel dónde tenía que estar un planeta nuevo, Neptuno, y se encontró enseguida. Este matrimonio no lo ve con su catalejo: en teoría estará, pero en la práctica, nada.",
      defensa: "Pregunta qué falla exactamente en la práctica: o hay un fallo concreto, o es una excusa." },
    { id: "interes", n: 35,
      titulo: "Toca el bolsillo, no la cabeza",
      tecnico: "Apelar a las consecuencias (ad consequentiam)",
      que: "No intentes convencer con razones: haz ver al otro, o al público, que su idea le perjudica. Schopenhauer decía que, si se puede usar, hace innecesarias todas las demás.",
      dialogo: [{ k: "buho", t: "Propongo dejar los móviles en casa en la excursión." }, { k: "zorro", t: "Ya, ¿y quién hará las fotos para vuestras redes?" }],
      img: "media/juegosucio/interes.jpg", w: 900, h: 731,
      obra: "Honoré Daumier, <em>Les Gens de justice</em>, lámina 6 (1845-1848).",
      pie: "«Un abogado que, evidentemente, está lleno de la convicción más íntima… de que su cliente le pagará bien.» A veces la razón más fuerte de alguien no es la que dice, sino lo que gana.",
      defensa: "Que algo no te convenga no lo hace falso. Separa «¿es verdad?» de «¿me interesa?»." },
    { id: "palabreria", n: 36,
      titulo: "Lía al otro con palabrería",
      tecnico: "Jerga vacía (ofuscación)",
      que: "Suelta frases largas y difíciles que suenan a muy sabias. El otro, por no parecer tonto, no se atreve a preguntar.",
      dialogo: [{ k: "zorro", t: "Desde una perspectiva holística, tu propuesta carece de sinergias." }, { k: "buho", t: "¿Y eso qué significa?" }],
      img: "media/juegosucio/palabreria.jpg", w: 900, h: 1276,
      obra: "Francisco de Goya, <em>Capricho 53: ¡Qué pico de oro!</em> (1799). Museo del Prado.",
      pie: "Un loro predica desde lo alto y un público de señores serios lo escucha embobado. Hablar bonito y difícil no es lo mismo que decir algo.",
      defensa: "Pregunta sin miedo: «¿Me lo explicas con palabras sencillas?»." },
    { id: "pruebamala", n: 37,
      titulo: "Tumba la prueba mala y da la idea por tumbada",
      tecnico: "Falacia de la falacia (ad logicam)",
      que: "Si el otro defiende una idea verdadera con una mala razón, ataca la razón y haz como si la idea fuera falsa.",
      dialogo: [{ k: "buho", t: "Fumar es malo porque lo dice mi abuela." }, { k: "zorro", t: "¡Tu abuela no es médica! O sea, que fumar no es malo." }],
      img: "media/juegosucio/pruebamala.jpg", w: 900, h: 750,
      obra: "Honoré Daumier, <em>Les Gens de justice</em>, lámina 17 (1845-1848).",
      pie: "«—Testigo, sería importante que nos contara con todo detalle qué hizo el pasado 12 de abril. —Pero, señor presidente, si hace nueve meses… —¡No importa, cuente!» Si el testigo no recuerda los detalles, parece que todo lo que dice es falso, aunque no lo sea.",
      defensa: "Una mala razón no hace falsa una idea: busca una razón mejor." },
    { id: "insultar", n: 38,
      titulo: "Si pierdes, insulta",
      tecnico: "Ataque a la persona (ad hominem)",
      que: "Es la última estratagema: cuando ya no tienes nada que decir, ataca a la persona en vez de a lo que dice. Schopenhauer aconseja no discutir con quien juega así.",
      dialogo: [{ k: "buho", t: "Tus datos están mal: aquí no viven cien millones de personas." }, { k: "zorro", t: "¡Y tú qué sabrás, si suspendiste mates!" }],
      img: "media/juegosucio/insultar.jpg", w: 900, h: 1196,
      obra: "Honoré Daumier, <em>Les Gens de justice</em>, lámina 32 (1845-1848).",
      pie: "«—Deje que hablen un poco mal de usted… deje… Dentro de un momento insultaré yo a toda la familia de su adversario.»",
      defensa: "«Puede ser, pero ¿mis datos están bien o mal?» Y si sigue insultando, deja la discusión." }
  ]
};
